BlogProject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('', include('diary.urls')),
]

blog/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'blog'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('post/<int:pk>/', views.detail, name='detail'),
    path('archives/<int:year>/<int:month>/', views.ArchiveView.as_view(), name='archive'),
    path('tag/<int:pk>/', views.TagView.as_view(), name='tag'),
    path('category/<int:pk>/', views.CategoryView.as_view(), name='category'),
    path('search/', views.search, name='search')
]

diary/urls.py
from django.urls import path, include
from . import views

app_name = 'diary'
urlpatterns = [
    path('niki', views.showDiary, name='index'),
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.utils.html import strip_tags
from django.urls import reverse
import markdown
from mdx_math import MathExtension

class FriendLink(models.Model):
    def __str__(self):
        return self.name

    url = models.CharField(max_length=120)
    name = models.CharField(max_length=100)

class Category(models.Model):
    def __str__(self):
        return self.name

    name = models.CharField(max_length=100)

class Tag(models.Model):
    def __str__(self):
        return self.name

    name = models.CharField(max_length=50)

class Post(models.Model):
    def __str__(self):
        return self.title

    def addViews(self):
        self.views += 1
        self.save(update_fields=['views'])

    def save(self, *args, **kwargs):
        self.modified_time = timezone.now()

        md = markdown.Markdown(extensions=[
            'markdown.extensions.extra',
            'markdown.extensions.codehilite',
            'markdown.extensions.toc',
            MathExtension(enable_dollar_delimiter=True)
        ])
        self.excerpt = strip_tags(md.convert(self.body))[:110]

        super().save(*args, **kwargs)

    def getAbsoluteURL(self):
        return reverse('blog:detail', kwargs={'pk': self.pk})

    title = models.CharField(max_length=70)

    body = models.TextField()

    created_time = models.DateTimeField(default=timezone.now)
    modified_time = models.DateTimeField()

    excerpt = models.CharField(max_length=200, blank=True)

    category = models.ForeignKey(Category, on_delete=models.CASCADE)

    tags = models.ManyToManyField(Tag, blank=True)

    author = models.ForeignKey(User, on_delete=models.CASCADE)

    views = models.PositiveIntegerField(default=0)

diary/models.py
from django.db import models
from django.utils import timezone

# Create your models here.

class Diary(models.Model):
    content = models.TextField()
    time = models.DateTimeField(default=timezone.now)

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import ListView
from pure_pagination import PaginationMixin
from django.contrib import messages
from django.db.models import Q

from .models import Post, Tag, Category
import markdown
from mdx_math import MathExtension
import re


class IndexView(PaginationMixin, ListView):
    model = Post
    template_name = 'blog/index.html'
    context_object_name = 'post_list'
    ordering = ['-created_time']
    paginate_by = 10


def detail(request, pk):
    post = get_object_or_404(Post, pk=pk)

    # 增加文章阅读量
    post.addViews()

    # 文章主题markdown转html
    md = markdown.Markdown(extensions=[
        'markdown.extensions.extra',
        'markdown.extensions.codehilite',
        'markdown.extensions.toc',
        'markdown.extensions.nl2br',
        MathExtension(enable_dollar_delimiter=True)
    ])
    post.body = md.convert(post.body)

    # 文章目录
    m = re.search(r'<div class="toc">\s*<ul>(.*)</ul>\s*</div>', md.toc, re.S)
    post.toc = m.group(1) if m is not None else ''

    return render(request, 'blog/detail.html', context={'post': post})


class TagView(IndexView):
    def get_queryset(self):
        t = get_object_or_404(Tag, pk=self.kwargs['pk'])
        return Post.objects.filter(tags=t).order_by('-created_time')


class CategoryView(IndexView):
    def get_queryset(self):
        c = get_object_or_404(Category, pk=self.kwargs['pk'])
        return Post.objects.filter(category=c).order_by('-created_time')


class ArchiveView(IndexView):
    def get_queryset(self):
        post_list = Post.objects.filter(
            created_time__year=self.kwargs['year'],
            created_time__month=self.kwargs['month']
        ).order_by('-created_time')
        return post_list


def search(request):
    q = request.GET.get('q')

    # 若查询为空则重定向至首页
    # if not q:
    #     messages.warning(request, '请输入搜索关键词')
    #     return redirect('blog:index')

    post_list = Post.objects.filter(Q(title__icontains=q) | Q(body__icontains=q))

    # 若未查询到则提示并重定向至首页
    if post_list.count() == 0:
        messages.info(request, '未检索到相关文章')
        return redirect('blog:index')

    return render(request, 'blog/index.html', {'post_list': post_list})


# def index(request):
#     post_list = Post.objects.all().order_by('-created_time')
#     return render(request, 'blog/index.html', context={'post_list': post_list})
#
# def archive(request, year, month):
#     post_list = Post.objects.filter(
#         created_time__year=year,
#         created_time__month=month
#     ).order_by('-created_time')
#     return render(request, 'blog/index.html', context={'post_list': post_list})
#
# def categories(request, pk):
#     c = get_object_or_404(Category, pk=pk)
#     post_list = Post.objects.filter(category=c).order_by('-created_time')
#     return render(request, 'blog/index.html', context={'post_list': post_list})
#
# def tags(request, pk):
#     t = get_object_or_404(Tag, pk=pk)
#     post_list = Post.objects.filter(tags=t).order_by('-created_time')
#     return render(request, 'blog/index.html', context={'post_list': post_list})

diary/views.py
from django.shortcuts import render
from .models import Diary
import markdown

# Create your views here.

def showDiary(request):
    diary_list = Diary.objects.all().order_by('-time')

    md = markdown.Markdown(extensions=[
        'markdown.extensions.extra',
        'markdown.extensions.codehilite',
        'markdown.extensions.toc',
        'markdown.extensions.nl2br',
    ])

    for diary in diary_list:
        diary.content = md.convert(diary.content)

    return render(request, 'diary/diary.html', {'diary_list': diary_list})

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="zh">
<head>
    <meta charset="UTF-8">
    <title>RennsのBlog</title>
    <link rel="icon" href="{% static 'blog/img/icon32.ico' %}">

    <!-- code highlight -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.4.0/styles/github.min.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'blog/css/highlight.css' %}">


    <!-- js -->
    <script src="{% static 'blog/js/jquery-3.6.0.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>

    <!-- css -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'blog/css/custom.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/detail.css' %}">

    <!-- latex -->
    <script type="text/x-mathjax-config">
        MathJax.Hub.Config({
        showProcessingMessages: false, //关闭js加载过程信息
        messageStyle: "none", //不显示信息
        extensions: ["tex2jax.js"],
        jax: ["input/TeX", "output/HTML-CSS"],
        tex2jax: {
            inlineMath:  [['$', '$']], //行内公式选择$
            displayMath: [ ["$$","$$"] ], //段内公式选择$$
            skipTags: ['script', 'noscript', 'style', 'textarea', 'pre','code','a'], //避开某些标签
        },
        "HTML-CSS": {
            availableFonts: ["STIX","TeX"], //可选字体
            showMathMenu: true //关闭右击菜单显示
        }
        });
        MathJax.Hub.Queue(["Typeset",MathJax.Hub]);
    </script>
{#    <script type="text/javascript" src="http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML"></script>#}
    <script type="text/javascript" async src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-MML-AM_CHTML"></script>

    <!-- debug  --> <!-- del mark -->
    <link rel="stylesheet" href="{% static 'blog/css/debug.css' %}">
</head>
<body>

{% if messages %}
    <script>
        {% for msg in messages %}
            alert('{{ msg.message }}')
        {% endfor %}
    </script>
{% endif %}

<header id="site-header">
    <div class="container">
        <div class="row">
            <div class="col-md-12 col-12">
                <h1 id="site-title"><a href="{% url 'blog:index'%}">RennsのBlog</a></h1>
            </div>
        </div>
    </div>
</header>

<div class="container" id="content">
    {% block main %}
    {% endblock main %}
</div>

<footer id="site-footer">
    <div class="container">
        <div class="row">
            <div class="col-md-12 col-12">
                <p class="copyright">Copyright &copy 2021-2023 by Renns</p>
            </div>
        </div>
    </div>
</footer>

<script src="{% static 'blog/js/script.js' %}"></script>

<!-- code highlight -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.4.0/highlight.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/highlightjs-line-numbers.js/2.8.0/highlightjs-line-numbers.js"></script>
<script>
    hljs.initHighlightingOnLoad();
    hljs.initLineNumbersOnLoad();
</script>
</body>
</html>

templates/blog/base_blog.html
{% extends 'base.html' %}
{% load static %}
{% load blog_extras %}

{% block main %}
    <div class="row">
        <main class="col-md-9" id="content-main">
            {% block content_main %}
            {% endblock content_main %}
        </main>
        <aside class="col-md-3" id="content-aside">
            <div id="about">
                <img src="{% static 'blog/img/avatar.png' %}" id="avatar">
                <hr>
                <div>
                    <h3 id="my-name">Renns</h3>
                    <p id="my-intro">
                        ACMer, OIer <br>
                        majored in CS at HITsz
                    </p>
                    <p id="contact">
                        <a href="https://github.com/niiickZ" title="Github">
                            <img src="https://inews.gtimg.com/newsapp_ls/0/14402097058/0.jpg">
                        </a>
                        <a href="mailto: niiick12848@163.com" title="niiick12848@163.com">
                            <img src="https://inews.gtimg.com/newsapp_ls/0/14402091753/0.png">
                        </a>
                        <a href="https://blog.csdn.net/niiick" title="CSDN">
                            <img src="https://p1.meituan.net/dpgroup/4203793aac5a57c02ab816cae1cef28a1221.jpg">
                        </a>
                    </p>
                </div>
            </div>

            {% block toc %}
            {% endblock toc %}

            {% showArchives %}

            <div id="search-box">
                <h3>搜索</h3>
                <form id="search-form" method="get" action="{% url 'blog:search' %}">
                    <input type="search" id="search-input" name="q" required maxlength="40">
                    <input type="submit" id="search-submit" value="搜索">
                </form>
            </div>

            {% showCategories %}
            {% showTags %}
            {% showFriendlinks %}
        </aside>
    </div>
{% endblock main %}

templates/blog/detail.html
{% extends 'blog/base_blog.html' %}
{% block content_main %}
    <article class="detail">
        <div class='toggle-wrap'>
            <div class='toggle-button'></div>
            <span class='toggle-text'>Full Screen</span>
        </div>
        <header>
            <h1 class="post-title">{{ post.title }}</h1>
            <div class="post-info">
                <span class="post-time">
                    <a href="{% url 'blog:archive' post.created_time.year post.created_time.month %}">{{ post.created_time.date }}</a>
                </span>
                <span class="post-visVolume">{{ post.views }} 阅读</span>
                <span class="post-tags">
                    Tag:
                    {% for tag in post.tags.all %}
                        <span><a href="{% url 'blog:tag' tag.pk %}">{{ tag.name }}</a></span>
                    {% endfor %}
                </span>
            </div>
        </header>
        <div class="detail-content">{{ post.body|safe }}</div>
    </article>
{% endblock content_main %}

{% block toc %}
    {% if post.toc %}
        <div id="catalogue">
            <h3>文章目录</h3>
            <div class="toc">
                <ul>
                    {{ post.toc|safe }}
                </ul>
            </div>
        </div>
    {% endif %}
{% endblock toc %}

templates/blog/inclusions/_archives.html
<div id="archives">
    <h3>归档</h3>
    <ul>
        {% for date in date_list %}
        <li><a href="{% url 'blog:archive' date.year date.month %}">{{ date.year }}年{{ date.month }}月</a></li>
        {% empty %}
            <li>暂无归档</li>
        {% endfor %}
    </ul>
</div>

templates/blog/inclusions/_category.html
<div id="category">
    <h3>分类</h3>
    <ul>
        {% for cate in cate_list %}
            <li><a href="{% url 'blog:category' cate.pk %}">{{ cate.name }} ({{ cate.num }})</a></li>
        {% empty %}
            <li>标签未创建</li>
        {% endfor %}
    </ul>
</div>

templates/blog/inclusions/_friends_link.html
<div id="friends_link">
    <h3>友链</h3>
    <ul>
        {% for link in link_list %}
            <li><a href="{{ link.url }}">{{ link.name }}</a></li>
        {% empty %}
            <li>咦？什么都没有呢</li>
        {% endfor %}
    </ul>
</div>

templates/blog/inclusions/_tag_cloud.html
<div id="tag-cloud">
    <h3>标签</h3>
    <ul>
        {% for tag in tag_list %}
        <li><a href="{% url 'blog:tag' tag.pk %}">{{ tag.name }} ({{ tag.num }})</a></li>
        {% empty %}
         <li>标签未创建</li>
        {% endfor %}
    </ul>
</div>

templates/blog/index.html
{% extends 'blog/base_blog.html' %}
{% block content_main %}
    {% for post in post_list %}
        <article class="post">
            <header>
                <h1 class="post-title"><a href="{{ post.getAbsoluteURL }}" target="_blank">{{ post.title }}</a></h1>
                <div class="post-info">
                    <span class="post-time">
                        <a href="{% url 'blog:archive' post.created_time.year post.created_time.month %}">{{ post.created_time.date }}</a>
                    </span>
                    <span class="post-visVolume">{{ post.views }} 阅读</span>
                    <span class="post-tags">
                        Tag:
                        {% for tag in post.tags.all %}
                            <span><a href="{% url 'blog:tag' tag.pk %}">{{ tag.name }}</a></span>
                        {% endfor %}
                    </span>
                </div>
            </header>
            <p class="post-excerpt">{{ post.excerpt }}</p>
            <div class="read-more">
                <a href="{{ post.getAbsoluteURL }}" target="_blank" class="more-link">继续阅读 <span>&rsaquo;&rsaquo;&rsaquo;</span></a>
            </div>
        </article>

    {% empty %}
        <div class="no-post">暂时还没有发布的文章！</div>
    {% endfor %}

    {% if is_paginated %}
        <div class="paging-bar">
            <ul>
                {% if page_obj.has_previous %}
                    <li><a href="?{{ page_obj.previous_page_number.querystring }}">&lsaquo;&lsaquo;Pre</a></li>
                {% else %}
                      <li><span class="disabled">&lsaquo;&lsaquo;Pre</span></li>
                {% endif %}

                {% for page in page_obj.pages %}
                    {% if page %}
                        {% ifequal page page_obj.number %}
                            <li><span class="current-page">{{ page }}</span></li>
                        {% else %}
                            <li><a href="?{{ page.querystring }}" class="page">{{ page }}</a></li>
                        {% endifequal %}
                    {% endif %}
                {% endfor %}

                {% if page_obj.has_next %}
                    <li><a href="?{{ page_obj.next_page_number.querystring }}">Nxt&rsaquo;&rsaquo;</a></li>
                {% else %}
                    <li><span class="disabled">Nxt&rsaquo;&rsaquo;</span></li>
                {% endif %}
            </ul>
        </div>
    {% endif %}
{% endblock content_main %}

templates/diary/diary.html
{% extends 'base.html' %}
{% block main %}
    <article class="detail">
        {% for diary in diary_list %}
            <div class="detail-content">
                <p><b>{{ diary.time }}</b></p>
                {{ diary.content|safe }}
            </div>
        {% endfor %}
    </article>
{% endblock main %}